#!/usr/bin/env node

/**
 * Build script to bundle browser code into a single injectable string
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import ts from 'typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// Handle both running from src/ (dev) and from .build.mjs (CI)
const browserDir = __dirname.endsWith('src') ? __dirname : join(__dirname, 'src');

const locatorCode = readFileSync(join(browserDir, 'locator.ts'), 'utf-8');
const actionsCode = readFileSync(join(browserDir, 'actions.ts'), 'utf-8');
const domtreeCode = readFileSync(join(browserDir, 'domtree.ts'), 'utf-8');

/**
 * Strip TypeScript types using the TypeScript compiler API
 */
function stripTypes(code: string): string {
  const result = ts.transpileModule(code, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.None, // No module system - functions stay at top level
      removeComments: true,
    },
  });

  return result.outputText;
}

// Combine all code into a single module context
const combinedCode = `
${locatorCode}

${actionsCode}

${domtreeCode}
`;

const bundle = `
(function() {
  'use strict';

  ${stripTypes(combinedCode)}

  // Return results as JSON
  window.__arcMCPResult = function(result) {
    return JSON.stringify(result);
  };
})();
`.trim();

// Write bundled JavaScript
writeFileSync(join(browserDir, 'bundle.js'), bundle);

// Export as TypeScript constant
const tsExport = `// Auto-generated by build.ts - do not edit manually
export const BROWSER_BUNDLE = ${JSON.stringify(bundle)};
`;

writeFileSync(join(browserDir, 'bundle-export.ts'), tsExport);

console.log('Browser bundle built successfully');
console.log(`Bundle size: ${bundle.length} bytes`);
