#!/usr/bin/env node

/**
 * Build script to bundle browser code into a single injectable string
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const browserDir = __dirname;

const locatorCode = readFileSync(join(browserDir, 'locator.ts'), 'utf-8');
const actionsCode = readFileSync(join(browserDir, 'actions.ts'), 'utf-8');
const domtreeCode = readFileSync(join(browserDir, 'domtree.ts'), 'utf-8');

/**
 * Strip TypeScript types and comments
 */
function stripTypes(code: string): string {
  return (
    code
      // Remove single-line comments
      .replace(/\/\/.*/g, '')
      // Remove multi-line comments
      .replace(/\/\*[\s\S]*?\*\//g, '')
      // Remove type annotations
      .replace(/:\s*\w+(\[\])?(\s*\|[^=]*)?/g, '')
      // Remove interface declarations
      .replace(/interface\s+\w+\s*\{[^}]*\}/g, '')
      // Remove type declarations
      .replace(/type\s+\w+\s*=[^;]+;/g, '')
      // Remove Record<...> generic types
      .replace(/:\s*Record<[^>]+>/g, '')
      // Remove as HTMLElement type assertions
      .replace(/as\s+HTML\w+/g, '')
      // Remove 'as any' type assertions
      .replace(/as\s+any/g, '')
      // Clean up extra whitespace
      .replace(/\n\s*\n\s*\n/g, '\n\n')
  );
}

const bundle = `
(function() {
  'use strict';

  ${stripTypes(locatorCode)}

  ${stripTypes(actionsCode)}

  ${stripTypes(domtreeCode)}

  // Return results as JSON
  window.__arcMCPResult = function(result) {
    return JSON.stringify(result);
  };
})();
`.trim();

// Write bundled JavaScript
writeFileSync(join(browserDir, 'bundle.js'), bundle);

// Export as TypeScript constant
const tsExport = `// Auto-generated by build.ts - do not edit manually
export const BROWSER_BUNDLE = ${JSON.stringify(bundle)};
`;

writeFileSync(join(browserDir, 'bundle-export.ts'), tsExport);

console.log('Browser bundle built successfully');
console.log(`Bundle size: ${bundle.length} bytes`);
